# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1a0ebdd3e2e062defda82530cb7f1afce99ae1d32d3640d152bb58095a9857ae4d822c855d76e87954508b91dc754f213885d09deab228208be7b92df08a0ab

test:
  secret_key_base: 671037d979523b46c55187cb126f3abb8cd887cb0517314e81d2277d6ad66c0dda8b25a03298b11c61c01f911a5ee6c24264e3a65afd40f83427d537c292ede2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
